gui:
  nerdFontsVersion: "3"
git:
  pagers:
    - colorArg: always
      pager: delta --dark --paging=never --features=arctic-fox
      # pager: delta --dark --paging=never --features=corvas
      # pager: delta --dark --paging=never --features=collared-torogon
      # pager: delta --dark --paging=never --features=calochortus-lyallii
os:
  edit: "nvim --server \"$NVIM\" --remote-expr \"luaeval('SwitchFromLazygit()')\" && nvim --server \"$NVIM\" --remote {{filename}}"
  editAtLine: "nvim --server \"$NVIM\" --remote-expr \"luaeval('SwitchFromLazygit()')\" && nvim --server \"$NVIM\" --remote +{{line}} {{filename}}"
promptToReturnFromSubprocess: false
